"""Brief formatting and output agent."""

from __future__ import annotations

from pathlib import Path
from datetime import datetime, timezone
from boardroom.models.brief import WeeklyBrief


def format_markdown(brief: WeeklyBrief) -> str:
    """Format a weekly brief as Markdown."""
    risks = "\n".join(f"- {r}" for r in brief.key_risks) or "- None identified"
    actions = "\n".join(f"- {a}" for a in brief.recommended_actions) or "- None"

    return f"""# Engineering Weekly Brief
**Period**: {brief.period_start} | **Generated**: {brief.generated_at[:10]} | **Industry**: {brief.industry}
**Health Score**: {brief.health_score}/100

---

{brief.narrative}

---

## Delivery signals

| Metric | Value |
|--------|-------|
| PRs merged | {brief.delivery.prs_merged} |
| Deployments | {brief.delivery.deployments} |
| Avg lead time | {brief.delivery.avg_lead_time_hours:.1f} hours |
| Change failure rate | {brief.delivery.change_failure_rate:.1f}% |
| Active contributors | {brief.delivery.active_contributors} |

## Sprint: {brief.sprint.sprint_name}

| Metric | Value |
|--------|-------|
| Completion | {brief.sprint.completed_points}/{brief.sprint.total_points} points ({brief.sprint.completion_rate:.0f}%) |
| Blocked items | {brief.sprint.blocked_items} |
| Goals met | {', '.join(brief.sprint.goals_met) or 'none'} |
| Goals at risk | {', '.join(brief.sprint.goals_at_risk) or 'none'} |

## Incidents

| Metric | Value |
|--------|-------|
| Total | {brief.incidents.total_incidents} |
| Critical | {brief.incidents.critical_incidents} |
| High | {brief.incidents.high_incidents} |
| Avg MTTR | {brief.incidents.avg_mttr_hours:.1f} hours |

## Key risks

{risks}

## Recommended actions

{actions}

## Compliance notes

{brief.compliance_notes}

---
*Generated by BoardroomBrief — github.com/brianpelow/BoardroomBrief*
"""


def save_brief(brief: WeeklyBrief, output_dir: str = "briefs") -> Path:
    """Save a brief to the output directory."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    filename = f"brief-{brief.period_start}.md"
    path = out / filename
    path.write_text(format_markdown(brief))
    return path